//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanDoTreEm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BANHANGEntities : DbContext
    {
        public DB_BANHANGEntities()
            : base("name=DB_BANHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_GIOHANG> CHITIET_GIOHANG { get; set; }
        public virtual DbSet<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual DbSet<CHITIET_PHIEUDAT> CHITIET_PHIEUDAT { get; set; }
        public virtual DbSet<DANHMUCSANPHAM> DANHMUCSANPHAM { get; set; }
        public virtual DbSet<GIAMGIA> GIAMGIA { get; set; }
        public virtual DbSet<GIOHANG> GIOHANG { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANG { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAM { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAP { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PHIEUDAT> PHIEUDAT { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<THUONGHIEU> THUONGHIEU { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
