//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanDoTreEm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAMGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAMGIA()
        {
            this.HOADON = new HashSet<HOADON>();
        }
    
        public string ID_GIAMGIA { get; set; }
        public Nullable<System.DateTime> THOIGIANGIAMGIA { get; set; }
        public Nullable<double> GIAMGIA1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON { get; set; }
    }
}
