//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanDoTreEm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }
    
        public string ID_HOADON { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public Nullable<double> GIAMGIA { get; set; }
        public Nullable<int> PHIVANCHUYEN { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public string TRANGTHAI { get; set; }
        public string ID_GIAMGIA { get; set; }
        public string ID_NHANVIEN { get; set; }
        public string ID_KHACHHANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual GIAMGIA GIAMGIA1 { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
