//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BanDoTreEm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIET_GIOHANG = new HashSet<CHITIET_GIOHANG>();
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
            this.CHITIET_PHIEUDAT = new HashSet<CHITIET_PHIEUDAT>();
        }
    
        public string ID_SANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public string THANHPHAN { get; set; }
        public string HUONGDANSUDUNG { get; set; }
        public string HUONGDANBAOQUAN { get; set; }
        public string HANSUDUNG { get; set; }
        public string UUTIENNOIBAT { get; set; }
        public string CHATLIEU { get; set; }
        public string SOLUONG { get; set; }
        public string KICHTHUOC { get; set; }
        public string THETICH { get; set; }
        public Nullable<int> TRONGLUONG { get; set; }
        public Nullable<int> DONGIABAN { get; set; }
        public Nullable<System.DateTime> NGAYSANXUAT { get; set; }
        public string DOTUOIPHUHOP { get; set; }
        public string LUUY { get; set; }
        public string HINHANH { get; set; }
        public string ID_THUONGHIEU { get; set; }
        public string ID_LOAISP { get; set; }
        public Nullable<int> DONGIANHAP { get; set; }
        public string ID_DANHMUCSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_GIOHANG> CHITIET_GIOHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PHIEUDAT> CHITIET_PHIEUDAT { get; set; }
        public virtual DANHMUCSANPHAM DANHMUCSANPHAM { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
